name: Validate Data Converters
on:
  push:
    branches:
      - main
  pull_request_target:
    paths:
      - 'VENDORS/**/uplink/**'
      - 'VENDORS/**/downlink/**'

jobs:
  build:
    name: Check data converters
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.2"
          architecture: "x64"
      - name: Install tb-rest-client
        run: |
          pip install tb-rest-client
      - name: Run Validation Script
        env:
          ENDPOINT: ${{ secrets.ENDPOINT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python3 data_converters_validator.py
